modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Breedable%20Killer%20Rabbit"
logoFile="icon.png"

[[mods]]
modId="breedablekillerrabbit"
version="3.4"
displayName="Breedable Killer Rabbit"
displayURL="https://serilum.com/mod/breedable-killer-rabbit"
authors="Rick South"
description='''A minimalistic configurable mod which makes the killer rabbit tamable and available by breeding.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.breedablekillerrabbit]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.breedablekillerrabbit]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"